indexYaml:
  path: /indexYaml
  controller: App\Controller\HomeController::indexYaml

app.swagger_ui:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
